[package]
name = "iot-central"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.9.1"
reqwest = { version = "0.11.12", default-features = false, features = ["json", "rustls-tls", "blocking"] }
serde = { version = "1.0.147", features = ["derive"] }
